### ISSUE TITLE
Book: Section 3A: Static Guarantees (draft)

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/wg#118]
What sort of Static Guarantees are possible with Rust?

**Comment by japaric** [comment]
Static guarantees is a topic that's too broad. This section was originally brought up in the context of "the static configuration pattern with embedded-hal implementation as an example".

So the section should probably be named "static configuration" or "type state applied to configuration" or just "type state applied to embedded".

**Comment by japaric** [comment]
This issue was moved to rust-embedded/book#5
