### ISSUE TITLE
Relocate Newsletters to their own Repo?

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/wg#163]
Do we want to move the newsletters to their own repo? This would take effect after today's (2018-08-12) newsletter.

Downsides:

* There isn't much throughput to that repo, right now we only have a newsletter every two weeks, though this may increase to once per week.
* Another repo to follow in the organization

Upsides:

* Changes to the newsletter doesn't clutter up the main `wg` repo
* It would be easier to set up a static site (`https://newsletter.rust-embedded.org`), if we want at some point.

CC @japaric @rust-embedded/resources

**Comment by japaric** [comment]
If we agree on making a website / blog as discussed in #148 the newsletters should be moved there and rendered as old blog posts, IMO.

**Comment by japaric** [comment]
Done in #198
