### ISSUE TITLE
IRC logger hosted or maintained by us

### ISSUE THREAD

**Issue by japaric** [rust-embedded/wg#171]
We have been used the logging service provided by the Tock project: [tockbot](https://bot.tockos.org/tockbot-moz/embedded-bot/), but it was down for the past week and it seems to be down again. We discussed in the last WG meeting switching to an IRC logger hosted or maintained by us and that has more people that can look after it.

Options:

- We could request [botbot.me](https://botbot.me/) to set up and maintain the logging service. I don't know what's their average uptime.

- We could host a [botbot instance](https://github.com/BotBotMe) ourselves. Tockbot is a botbot instance.

- We could use something else. @thejpster mentioned that the selenium projects [logs everything to GitHub](https://github.com/SeleniumHQ/irc-logs/tree/master/2015/09).

Any solution you would recommend? Or should we stick to one of the above solutions?

cc @rust-embedded/all

**Comment by levex** [comment]
I like the idea of hosting the logs on GitHub a lot! I can imagine myself cloning the repo and `grep`ing through it for some information without having to use an often clunky web UI.

BotBotMe seems to have not been active for the past few months, what about using the following bot?
https://mozilla.logbot.info/

It seems to be part of Mozilla IRC, already.

**Comment by adamgreig** [comment]
:+1: for using logbot, it seems like an easy solution and already in use by a bunch of rust channels.

**Comment by japaric** [comment]
Using logbot SGTM

**Comment by japaric** [comment]
To move things forward here I'd like to propose (a) starting out with logbot and (b) postpone revisiting doing our own thing.

I'm going to nominate voting on the above proposal during the next meeting.
