### ISSUE TITLE
Jlink RTT support crate, primarily useful for Cortex-M0

### ISSUE THREAD

**Issue by wez** [rust-embedded/wg#200]
Not sure how best to communicate about this, so forgive me if this isn't quite the right place.
While poking at USB support for atsamd21, I needed a faster logging channel than semihosting is capable of providing.
Since I have a JLink it was super convenient to whip up logging and panic handling for the RTT protocol implemented by those devices.

The repo is here and could do with a little more expansion of its docs:
https://github.com/wez/jlink_rtt

I'd appreciate feedback on the code itself (it's relatively quick and dirty as it stands now), but mostly I'm posting here as a bit of a heads-up for the cortex-m team.

**Comment by eldruin** [comment]
RTT is now supported through [probe-rs](https://probe.rs). We agreed in today's WG meeting to close this. Please feel free to report further ideas over there.
