### ISSUE TITLE
Help with ideas / material for conference presentation for C++ metaprogrammers 

### ISSUE THREAD

**Issue by korken89** [rust-embedded/wg#281]
Hi all,

I made this issue to get some ideas on how to compare C++ template/`constexpr` metaprogramming with macros and procedual macros for [Embo++](http://www.embo.io) (maybe also a little `const-fn`).
One of the reasons C++ programmers stay there is due to the power of metaprograming gives them, and I'd like to show how we can use (proc-)macros to do more or less the same.
I talked a bit to one of the big names and conference organizer in embedded C++ (Odin Holmes) and they really would like a talk on this topic.

Hope we can get some ideas here! I'm also very open to have people collaborate/co-present this with me at embo if we get some ideas for materials!
I only need to make a short abstract for the talk to send to the conference, and then to actually make the presentation is until March.

Possible title (to get interest as well): "C++ metamagicians' guide to Rust"

**Comment by eldruin** [comment]
This already happened so closing. It would be great if you publish any materials you made!
