### ISSUE TITLE
Survey: unstable features you routinely (have to) use

### ISSUE THREAD

**Issue by japaric** [rust-embedded/wg#31]
This goal of this survey is to get an idea of what (currently) unstable Rust features would need to be stabilized to make embedded development feasible on the stable channel.

One unstable feature per comment. If an unstable feature you use is already listed in the comments up vote it (:+1: reaction) so we can track the number of users that feature has.

**Comment by japaric** [comment]
Xargo

**Comment by japaric** [comment]
`#[lang_item = "panic_fmt"]` (`#![feature(lang_items)]`)

**Comment by japaric** [comment]
`extern crate compiler_builtins` (`#![feature(compiler_builtins)]`)

**Comment by japaric** [comment]
`asm!` (`#![feature(asm)]`)

**Comment by japaric** [comment]
`#[linkage = "weak"]` (`#![feature(linkage)]`)

**Comment by japaric** [comment]
`#[naked]` (`#![feature(naked_functions)]`)

**Comment by japaric** [comment]
`#[used]` (`#![feature(used)]`)

**Comment by japaric** [comment]
`const fn foo()` (`#![feature(const_fn)]`)

**Comment by japaric** [comment]
`core::intrinsics` (`#![feature(core_intrinsics)]`)

**Comment by japaric** [comment]
`global_asm!()` (`#![feature(global_asm)]`)

**Comment by coder543** [comment]
Just being able to build even the tiniest, most incomplete functional firmware in Rust completely using the stable toolchain is the first step. Anything else is secondary, but a lot of those secondary items are important. Specifically, that primarily means `lang_items`, I think. For practical embedded usage, the standard `asm!` macro is the very next thing on the list.

Everything on this informal survey is definitely useful to embedded developers. However, as an example, stabilizing weak linkage will not get anyone closer to compiling a minimal embedded example with the stable toolchain if `lang_item` is not available, so I feel like the very most important stuff on this list is already a known factor.

**Comment by japaric** [comment]
@coder543 I agree with everything you said. *We*, embedded developers, know what's required for "being able to build even the tiniest, most incomplete functional firmware in Rust completely using the stable toolchain" and what's "the very next thing on the list" but the Rust team doesn't -- they are not embedded developers. That's where this survey can help. I can tell (and I already have) the Rust team that the number one blocker for stable no-std application development is the `panic_fmt` lang item, but if I add "and 100% of N developers agree" to the message then that adds a sense of urgency.

**Comment by japaric** [comment]
PSA: rust-lang/rfcs#2070 proposes a stable mechanism to specify the behavior of `panic!` in no-std context; this mechanism would supersede the unstable `panic_fmt` lang item.

cc @adamgreig @therealprof @coder543 @pftbest @parched @Michael-F-Bryan @lexxvir @cmerrill

**Comment by jamesmunns** [comment]
I think we met most of these goals, or have opened follow on issues for most items listed here. Nominating this to be closed.

**Comment by jamesmunns** [comment]
I am closing this issue, please feel free to open another issue if you would like this discussed further.
