### ISSUE TITLE
Maintainer for the stm32f30x-hal repository

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/wg#312]
The `stm32f30x-hal` repository would benefit from an additional maintainer (https://github.com/japaric/stm32f30x-hal/issues/22).
In [this meeting](https://github.com/rust-embedded/wg/blob/768a21a7d69da766b7191f568df3a7b97bad6d20/minutes/2018-07-30.md) it was proposed that the HAL team would maintain it but in the team list I cannot see that this is the case. Maybe this slip through or so.
Nowadays there is also the stm32-rs org, which is also an option.
Being `stm32f30x-hal` "the canonical implementation" I would understand extra caution here.

**Comment by jonas-schievink** [comment]
That HAL is now mostly obsolete and replaced by https://github.com/stm32-rs/stm32f3xx-hal, so closing.
