### ISSUE TITLE
Embedded WG meeting, March 5

### ISSUE THREAD

**Issue by Disasm** [rust-embedded/wg#326]
[8-9 PM CET][0] (Berlin time) on #rust-embedded on irc.mozilla.org

[0]: https://everytimezone.com/#2019-03-05,420,b8jj

[Public Google calendar that includes these weekly meetings](https://calendar.google.com/calendar?cid=NzhmdGJsMGQ1cjA2YzM5dDJ1MDU0ODBsbm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

Agenda.

-  Reminders / announcements

- @flip111 svd2rust-like tool for external device specification - https://github.com/rust-embedded/wg/issues/22#issuecomment-464929863, bindings for [lvgl](https://github.com/littlevgl/lvgl)

- [Newsletter 16](https://github.com/rust-embedded/blog/blob/master/content/2019-03-06-newsletter-16.md)

- [Issues nominated for discussion, if any](https://github.com/rust-embedded/wg/labels/nominated)

- [your topic goes here]

This meeting is open for anyone to attend. If you'd like to bring up any issue / topic related to embedded Rust leave a comment in this issue so we can add it to the agenda.

**Comment by flip111** [comment]
Maybe it would be nice to have bindings for https://github.com/littlevgl/lvgl micropython already has bindings for it

**Comment by japaric** [comment]
This meeting happened! The logs and minutes can be found in #332.

The agenda for the next meeting is at #331
