### ISSUE TITLE
Oxidize Coordination

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/wg#346]
A number of /wg members will be attending [OxidizeConf](https://oxidizeconf.com) in Berlin. If you plan to be here, let's try and coordinate time for the teams to meet and discuss things, such as #265.

CC @rust-embedded/all

**Comment by jamesmunns** [comment]
I will be there for the conference and both Impl days (Sunday and Monday), though I may be running around organizing things.

**Comment by korken89** [comment]
I'll be there until Sunday afternoon.

**Comment by therealprof** [comment]
I'll be there on Saturday only.

**Comment by thejpster** [comment]
I'm there all four days

**Comment by Disasm** [comment]
I'll be there for all four days.

**Comment by japaric** [comment]
I'll be there for the four days (but I'm not attending any workshop).

**Comment by hannobraun** [comment]
I'll be there all 4 days. I'll also have some time the day before (late afternoon and evening) and the day after (morning and possibly early afternoon), in case anyone wants to meet.

**Comment by adamgreig** [comment]
I'm there from Friday evening until Monday afternoon.

**Comment by adamgreig** [comment]
This happened :tada:
