### ISSUE TITLE
Selecting a new rust-embedded communication channel

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/wg#349]
# Proposal for selecting a new communication channel

## Background

As people may have noticed **irc.mozilla.org** which is the main communication channel for the rust-embedded WG and community is coming to an end, cf. [here](http://exple.tive.org/blarg/2019/04/26/synchronous-text/) and also [here](https://blog.rust-lang.org/2019/04/26/Mozilla-IRC-Sunset-and-the-Rust-Channel.html).

While this change is going to take effect only in a few months from now this is the right time to decide which action to take forward and chose for a proper replacement.

## A choice to make

The reasons for Mozilla to abandon IRC and to look for an alternative means of communication have been documented but the replacement is still under evaluation which means this not a straight forward and/or simple choice to make which does certainly not simplify the situation of the WG as one of the few remaining IRC users. Other Rust teams and WGs have chosen [Discord](https://discordapp.com) (in fact there's an embedded channel on the [official Rust "server"](https://discord.gg/zZySVrF) if you'd like to say hello) or [Zulip](https://zulipchat.com/) a few years back which all have certain advantages and drawbacks and certainly does not mean an automatic decision for us.

## Power to the community

Since the main communication channel of the embedded WG is not only used for communication between the team members but also to engage with the community I propose to have the community allow to voice which communication channel they'd like to see in the future instead of having a closed inner circle decision forcing a solution on everyone. While it is very clear that there is not going to be a communication form which will please everyone, the user base has grown quite considerably over the last few years and users might have a vastly difference preference for engaging than the established inner circle which is quite well versed in an ancient protocol like IRC and may prefer to keep it (or not).

## Selection proposal

Some team members spent some effort identifying the most promising contenders which I propose should serve the base for a decision, unless additional suitable proposals are made (in alphabetical order):
* Discord
* Gitter
* IRC
* Matrix
* Zulip

## Community vote

As said it seems to make sense to sense to let the whole user base cast a vote on the preferred communication channel. The method this would work is by putting each candidate in its own post in a GH issue and, announce the vote on all available channels and count the number of all upvotes (👍) on each candidate after a fixed period of 2 weeks. Multiple choices are allowed and if the 2 highest results are within 3 votes of each other there will be a second ballot with only the 2 highest ranking options. In case of a real tie in that second ballot the @rust-embedded/core members will break the tie.

**Comment by jamesmunns** [comment]
Closed by #351
