### ISSUE TITLE
Providing guidance for MSRVs

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/wg#382]
At the EWG meeting 2019-10-15, we discussed providing guidance on how to use MSRVs. This should probably be added to https://github.com/rust-embedded/wg/blob/master/ops/msrv.md.

The guidance should be around:

* What authors of HAL crates should do (the current guidance is only for EWG crates)
* How to check what your MSRV is
* Pointers to the docs (and hence current MSRV) of EWG architecture crates like `cortex-m`.
* Some key features (such as `core::convert::Infallible`) and their MSRV

Steps:

* [ ] Open a PR
* [ ] Get approval
* [ ] Merge the PR
* [ ] Profit

**Comment by MarcoIeni** [comment]
I don't know if this the right place to ask for this, but it would be nice to have guidance for MSRV in Github actions
[here](https://github.com/rust-embedded/wg/blob/master/ops/post-transfer.md#ci-via-github-actions-gha).
For example the `1.35.0` is only mentioned [here](https://github.com/rust-embedded/wg/blob/master/ops/post-transfer.md#add-a-githubborstoml-file-with-these-contents) and not in other parts of the document.

**Comment by BartMassey** [comment]
Closing this as part of 2024 triage. MSRV issues were resolved by #523.
