### ISSUE TITLE
Agenda for 2020-01-14 meeting

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/wg#413]
[8-9 PM CET][0] (Berlin time) on [#rust-embedded:matrix.org](https://matrix.to/#/#rust-embedded:matrix.org)

[0]: https://everytimezone.com/?t=5deee000,474

[Public Google calendar that includes these weekly meetings](https://calendar.google.com/calendar?cid=NzhmdGJsMGQ1cjA2YzM5dDJ1MDU0ODBsbm9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

## Agenda 

* `cortex-m` exposes unsafe cache invalidation operations as safe https://github.com/rust-embedded/cortex-m/issues/188
* The road to 1.0:
  * Proposal to reshape `svd2rust` generated code: https://github.com/rust-embedded/svd2rust/issues/427
  * Change PAC API exposed by `svd2rust` to reduce chaining (and formatting woes)
  * Change the way we manage `embedded-hal` (aka gettting rid of `unproven` feature flag): https://github.com/rust-embedded/embedded-hal/issues/163
  * https://github.com/rust-embedded/cortex-m/issues/186
  * https://github.com/rust-embedded/cortex-m-rt/issues/237
* Transfer https://github.com/japaric/msp430-quickstart to rust-embedded?

---

This meeting is open for anyone to attend. If you'd like to bring up any issue / topic related to embedded Rust leave a comment in this issue so we can add it to the agenda.

**Comment by jonas-schievink** [comment]
We can also discuss https://github.com/rust-embedded/cortex-m/issues/186 and https://github.com/rust-embedded/cortex-m-rt/issues/237 if we have time (they're also part of the road to 1.0).

**Comment by jonas-schievink** [comment]
Speaking of changing the svd2rust generated code, I was thinking of changing the API of the register writers so that they make use of traits instead of endlessly chaining fields and values as method calls. So something like `.field().set_bit().field2().variant(Field2::Yes)` would become `.field(true).field2(Field2::Yes)`.

This makes the written code look somewhat cleaner IMO, but the real motivation is unblocking https://github.com/rust-embedded/wg/pull/289. Rustfmt makes the method-chaining-based API look very unreadable since it puts each method call in its own line (https://github.com/rust-embedded/wg/pull/289#issuecomment-452841162).

**Comment by therealprof** [comment]
@jonas-schievink Updated accordingly. Feel free to update the issue yourself.

**Comment by thejpster** [comment]
Although of course you don't have to chain them.

```
w.field().set_bit();
w.field().baud(19200);
```

I agree that `w.field(true)` is nicer though. Maybe adding `w.set_field(true)` is more backwards compatible.

**Comment by almindor** [comment]
I might be wrong but isn't `w.set_bit()` constant (compile time) while `w.set_bit(true)` makes it a runtime expense?

My understanding was that that's the reason why things like `Iterator::rev()` don't have a param.

**Comment by jonas-schievink** [comment]
No, both are entirely up to the optimizer. svd2rust marks all of those small functions `#[inline(always)]` to help with that, but that is also just a (strong) hint to the compiler. In practice both should always be optimized out though.

**Comment by hannobraun** [comment]
> Speaking of changing the svd2rust generated code, I was thinking of changing the API of the register writers so that they make use of traits instead of endlessly chaining fields and values as method calls. So something like `.field().set_bit().field2().variant(Field2::Yes)` would become `.field(true).field2(Field2::Yes)`.

I don't currently have a strong opinion, but I'd like to note that the proposed style requires the user to import the parameter types, which can be a hassle.

**Comment by jonas-schievink** [comment]
@hannobraun That's a good point actually! I think it does match other Rust builder patterns well though.

There might also be a tradeoff regarding compile times here. Do the methods compile faster, or the trait-based approach?

**Comment by almindor** [comment]
The more I think about this the more I think we should keep it as-is. Changing functional well understood code to workaround a formatter issue seems backwards.
