### ISSUE TITLE
Tracking Issue for implementation of RFC419

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/wg#428]
c.f. https://github.com/rust-embedded/wg/pull/419

**Comment by leo60228** [comment]
For what it's worth, rp2040-hal is the first HAL that's run directly into this (to my knowledge), and it just ignores the unsoundness. I don't think this is a great situation.

**Comment by BartMassey** [comment]
Closing this as part of 2024 triage. #419 was merged.
