### ISSUE TITLE
Tracking issue - Implement mutex trait in all arch crates

### ISSUE THREAD

**Issue by korken89** [rust-embedded/wg#448]
Remove mutex implementation from `bare-metal` and add new to arch specific crates.

- cortex-m https://github.com/rust-embedded/cortex-m/pull/209
- risc-v
- msp430
- more?

**Comment by Dirbaio** [comment]
Closing this as part of 2024 triage.

the `mutex-trait` crate is superseded by [`critical-section`](https://docs.rs/critical-section), which also allows writing code using mutexes portably across archs. Most arch-support crates already implement it.
