### ISSUE TITLE
Automate process of building docs for docs.rust-embedded.org

### ISSUE THREAD

**Issue by markhildreth** [rust-embedded/wg#457]
When accessing any of the three books from the `docs.rust-embedded.org` domain, the version of the documents received are over two months out of date, dating back to March 15th.

```
> date
Fri May 29 15:40:13 EDT 2020
> curl -s --head "https://rust-embedded.github.io/discovery/" | grep last-modified
last-modified: Thu, 28 May 2020 02:46:55 GMT
> curl -s --head "https://docs.rust-embedded.org/discovery/" | grep last-modified
last-modified: Sun, 15 Mar 2020 19:52:23 GMT
> curl -s --head "https://rust-embedded.github.io/book/" | grep last-modified
last-modified: Fri, 29 May 2020 17:35:25 GMT
> curl -s --head "https://docs.rust-embedded.org/book/" | grep last-modified
last-modified: Sun, 15 Mar 2020 19:52:23 GMT
> curl -s --head "https://rust-embedded.github.io/embedonomicon/" | grep last-modified
last-modified: Tue, 21 Apr 2020 17:28:25 GMT
> curl -s --head "https://docs.rust-embedded.org/embedonomicon/" | grep last-modified
last-modified: Sun, 15 Mar 2020 19:52:23 GMT
```

Additionally, the bookshelf is also out of date:

```
> curl -s --head "https://docs.rust-embedded.org" | grep last-modified
last-modified: Sun, 15 Mar 2020 19:52:23 GMT
```

This is because the `docs.rust-embedded.org` domain looks specifically to the `/docs` repository, which uses submodules to pull in the other book repositories. Unfortunately, there doesn't appear to be any automated system (or if there is, it is not working) to rebuild the `gh-pages` branch in the `/docs` repo enough to keep them up to date.

**Comment by adamgreig** [comment]
I believe that's because those are all generated/hosted via https://github.com/rust-embedded/docs/tree/gh-pages which has each book as a submodule. Not necessarily a great system...

**Comment by markhildreth** [comment]
@adamgreig Ah, didn't realize they were all in that repo. Is there a system in place that should be automating this that isn't working, or is there no such automatic system in place yet?

**Comment by adamgreig** [comment]
I'm not sure actually. I don't see anything that would cause a regular build to run, but such things are possible to have on Travis.

**Comment by yerke** [comment]
Fixed with https://github.com/rust-embedded/docs/pull/24
