### ISSUE TITLE
Rust embedded community logo based on EWG logo

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/wg#482]
We want to add a logo to the [rust-embedded-community](https://github.com/rust-embedded-community).
We liked a logo based on the EWG logo so it would be appropriate to ask here for approval.
Here is the proposed logo:
![rec-logo-250x250](https://user-images.githubusercontent.com/43125/87984526-5f5f8c00-cada-11ea-918a-41db87ede6a0.png)
[Discussion issue](https://github.com/rust-embedded-community/meta/issues/3)
Opinions? Concerns?

Licensing:
This logo proposal is based on the Rust Embedded Working Group logo which was designed by Erin Power, licensed under the Creative Commons Attribution License and is itself based on the Rust Language logo.
See [here](https://github.com/rust-embedded-community/meta/issues/4) for further info.

Edit (@jamesmunns): Corrected Erin's name

**Comment by therealprof** [comment]
As discussed in the meeting, this should be clarified with the Rust core team and get a written permission regarding the Rust trademark.

**Comment by therealprof** [comment]
cc https://github.com/rust-embedded-community/meta/issues/3

**Comment by eldruin** [comment]
A summary of the options as requested in the last meeting would be:

- Adopt REC as a child REWG org
    - Membership requirements TBD.
    - Maybe the original logo proposal would be acceptable (needs re-evaluation by core team)
- REC stays as a separate org.
    - Needs alternative logo to original proposal.
        - Ferris-based one may be too similar to REWG's.
    - REC name deemed confusing w.r.t. REWG.
        - New name necessary.
    - REC name deemed fine w.r.t. confusion with REWG.
        - Name stays as-is.

**Comment by eldruin** [comment]
I added an initial RFC with the terms for adopting REC as a child org at https://github.com/rust-embedded/wg/pull/504.

**Comment by eldruin** [comment]
Closing as the RFC will not be merged.
