### ISSUE TITLE
Implementer Wanted for Instruction Set RFC

### ISSUE THREAD

**Issue by Lokathor** [rust-embedded/wg#496]
Hello all.

The RFC for allowing [per-function instruction set selection](https://github.com/rust-lang/rfcs/blob/master/text/2867-isa-attribute.md) has been accepted ([tracking issue](https://github.com/rust-lang/rust/issues/74727)).

However, it doesn't have anyone available to actually implement it in the compiler. So I'm reaching out here in case anyone in the working group thinks they can tackle the issue.

**Comment by niclashoyer** [comment]
@Lokathor I think this is solved now, isn't it? https://github.com/rust-lang/rust/pull/76260

**Comment by Lokathor** [comment]
oh, yes.
