### ISSUE TITLE
Support `riscv32imf-unknown-none-elf (Baremetal)` in rust as a cross compile target?

### ISSUE THREAD

**Issue by Ma-Y** [rust-embedded/wg#645]
is there a way to do this?

**Comment by Ma-Y** [comment]
i think i found the

**Comment by Emilgardis** [comment]
Just leaving this here.

You'd need to define a [`target.json` file](https://doc.rust-lang.org/rustc/targets/custom.html) and then invoke `cargo build --target target.json`

see also the [embedonomicon](https://docs.rust-embedded.org/embedonomicon/custom-target.html)
