### ISSUE TITLE
Maintenance of meta-rust-bin

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/wg#698]
I randomly noticed that [meta-rust-bin](https://github.com/rust-embedded/meta-rust-bin) does not have a documented maintainer team.
Who is responsible for it?
@rust-embedded/tools ?
@rust-embedded/embedded-linux ?

**Comment by thejpster** [comment]
@rust-embedded/embedded-linux surely?

**Comment by posborne** [comment]
Yeah, @rust-embedded/embedded-linux should be the owner.  @nastevens and I wrote and have done most of the maint activities.  There's now rust support in upstream Yocto based on meta-rust but meta-rust-bin still is used and supports a slightly different integration model for rust code in distros based on Yocto.
