### ISSUE TITLE
Transfer heapless and volatile-register to libs team

### ISSUE THREAD

**Issue by adamgreig** [rust-embedded/wg#710]
I propose (with @japaric's blessing!) transferring [heapless](https://github.com/japaric/heapless) and [volatile-register](https://github.com/japaric/volatile-register) repos to the WG under the libs team. Heapless is widely used across the embedded ecosystem but the current maintainers don't have much time for updates, while volatile-register is used by cortex-m and we'd like to at least fix a soundness issue for us and other users (https://github.com/rust-embedded/cortex-m/issues/485). The newly formed libs team is a perfect fit, not coincidentally.

I hope we'll have a few more members soon, now that the team exists. Still, the current libs team should vote:

- [x] @Dirbaio 
- [x] @newAM

**Comment by Dirbaio** [comment]
I vote yes :laughing:

**Comment by newAM** [comment]
I vote yes!  ♥️ heapless

**Comment by japaric** [comment]
> I propose (with @japaric's blessing!) transferring [heapless](https://github.com/japaric/heapless) and [volatile-register](https://github.com/japaric/volatile-register) repos to the WG under the libs team

I'm on board :+1: (let me know when / where to transfer the repos)

**Comment by Dirbaio** [comment]
I don't think there's any blocker left? you can transfer to https://github.com/rust-embedded, @adamgreig will have to configure the permissions I guess.

**Comment by adamgreig** [comment]
> I'm on board 👍 (let me know when / where to transfer the repos)

Thanks! Just transfer them to rust-embedded any time, I'll then assign them to the libs team.

**Comment by japaric** [comment]
done!

- https://github.com/rust-embedded/heapless
- https://github.com/rust-embedded/volatile-register

**Comment by adamgreig** [comment]
Thank you! I've put them under the libs team now. Could you add the team on crates.io as well, please?

```
cargo owner --add github:rust-embedded:libs
```

**Comment by adamgreig** [comment]
@rust-embedded/libs, there's some notes in https://github.com/rust-embedded/wg/blob/master/ops/post-transfer.md about the changes to make, which for this I think boil down to:

* [ ] update wg/README.md with new repos
* [ ] update repo READMEs with reference to the libs team and CoC
* [ ] add CoC file to repo
* [ ] update repo `.github/CODEOWNERS` with `* rust-embedded/libs`
* [ ] possibly set up GHMQ/required CI checks if desired

**Comment by japaric** [comment]
@adamgreig it seems like I need to be temporarily added to the `libs` team to do that:

``` console
$ cargo owner --add github:rust-embedded:libs
error: failed to invite owners to crate `heapless` on registry at https://crates.io

Caused by:
  the remote server responded with an error: only members of a team or organization owners can add it as an owner
```

**Comment by adamgreig** [comment]
Huh, I didn't know that! I wonder if it's a recent change. Could you add me as an owner directly instead, then? At least that also avoids not being able to update owners in future, and I should be able to add the libs team.

**Comment by japaric** [comment]
@adamgreig crates.io invites sent!

**Comment by adamgreig** [comment]
Thanks, all sorted!

**Comment by Dirbaio** [comment]
all done! thanks guys :partying_face:
